export const TEMPLATE_CATALOG = [
  { id: 'modern', label: 'Modern', color: '#0f766e', desc: 'Clean teal accents with strong hierarchy. Perfect for tech and startup roles.', tags: ['Tech', 'Startup', 'Design'], featured: true },
  { id: 'classic', label: 'Classic', color: '#1e3a5f', desc: 'Traditional navy layout, ideal for corporate, finance, and legal roles.', tags: ['Corporate', 'Finance', 'Legal'], featured: true },
  { id: 'minimal', label: 'Minimal', color: '#64748b', desc: 'Ultra-clean, whitespace-forward design. Lets your content speak loudly.', tags: ['Any Industry', 'Creative', 'Senior'], featured: true },
  { id: 'executive', label: 'Executive', color: '#8B0000', desc: 'Dark header, premium feel. Built for leadership and C-suite positions.', tags: ['Executive', 'Leadership', 'Management'], featured: true },
  { id: 'creative', label: 'Creative', color: '#7c3aed', desc: 'Bold sidebar layout with vibrant purple. Perfect for designers and marketers.', tags: ['Design', 'Marketing', 'Creative'], featured: true },
  { id: 'tech', label: 'Tech / Dev', color: '#00b4d8', desc: 'Monospace font, code-aesthetic layout. Built for engineers and developers.', tags: ['Engineering', 'Backend', 'Full-stack'], featured: true },
  { id: 'ats', label: 'ATS-Friendly', color: '#2d3748', desc: 'Optimized for Applicant Tracking Systems with simple formatting. Maximizes parsing accuracy.', tags: ['All Industries', 'Job Hunt', 'Simple'] },
  { id: 'academic', label: 'Academic', color: '#6b4226', desc: 'Designed for researchers and academics with sections for publications and research.', tags: ['Academic', 'Research', 'University'] },
  { id: 'functional', label: 'Functional', color: '#c7254e', desc: 'Skills-focused layout emphasizing abilities over chronological work history. Great for career changers.', tags: ['Career Change', 'Skills', 'Freelance'] },
  { id: 'portfolio', label: 'Portfolio', color: '#d63384', desc: 'Showcase your projects and portfolio with links. Perfect for designers and developers.', tags: ['Design', 'Development', 'Portfolio'] },
  { id: 'minimalist', label: 'Minimalist Monochrome', color: '#000000', desc: 'Black and white elegance. Ultra-professional with maximum readability.', tags: ['Professional', 'Formal', 'Legal'] },
  { id: 'colorful', label: 'Vibrant', color: '#ff6b35', desc: 'Playful design with bold colors and creative sections. Perfect for creative industries.', tags: ['Creative', 'Marketing', 'Design'] },
  { id: 'healthcare', label: 'Healthcare', color: '#0ea5e9', desc: 'Specialized for medical professionals with sections for licenses and certifications.', tags: ['Healthcare', 'Medical', 'Nursing'] },
  { id: 'finance', label: 'Finance', color: '#15803d', desc: 'Professional layout with emphasis on achievements and financial metrics.', tags: ['Finance', 'Banking', 'Accounting'] },
  { id: 'sales', label: 'Sales & Business', color: '#f59e0b', desc: 'Achievement-focused layout highlighting targets met and revenue impact.', tags: ['Sales', 'Business', 'Marketing'] },
  { id: 'timeline', label: 'Timeline', color: '#8b5cf6', desc: 'Chronological timeline-based layout showing career progression visually.', tags: ['Career', 'Progressive', 'Visual'] },
  { id: 'dark', label: 'Dark Mode', color: '#1f2937', desc: 'Modern dark theme with light text. Contemporary and trendy appeal.', tags: ['Modern', 'Tech', 'Trendy'] },
  { id: 'gradient', label: 'Gradient', color: '#6366f1', desc: 'Beautiful gradient backgrounds with modern styling. Visually striking design.', tags: ['Design', 'Creative', 'Modern'] },
  { id: 'twocolumn', label: 'Two-Column', color: '#059669', desc: 'Side-by-side layout with left sidebar for quick facts and right for details.', tags: ['Organized', 'Balanced', 'Clear'] },
  { id: 'retro', label: 'Retro/Vintage', color: '#dc2626', desc: 'Classic retro design with vintage typography and warm colors. Unique personality.', tags: ['Unique', 'Creative', 'Personality'] },
  { id: 'bold', label: 'Bold Header', color: '#ea580c', desc: 'Strong dominant header with impactful visual presence. Makes an impression.', tags: ['Leadership', 'Standout', 'Executive'] },
  { id: 'elegant', label: 'Elegant', color: '#b91c8c', desc: 'Sophisticated layout with elegant fonts and refined spacing. Premium feel.', tags: ['Professional', 'Luxury', 'Refined'] },
  { id: 'minimalist2', label: 'Ultra Minimal', color: '#9ca3af', desc: 'Extreme minimalism with maximum whitespace. True essence of simplicity.', tags: ['Simple', 'Clean', 'Zen'] },
  { id: 'industech', label: 'InduTech', color: '#1e40af', desc: 'Industrial design with tech elements. For engineering and technical roles.', tags: ['Engineering', 'Industrial', 'Technical'] },
  { id: 'startup', label: 'Startup', color: '#ec4899', desc: 'Trendy startup culture design with modern patterns and bold accents.', tags: ['Startup', 'Innovation', 'Trendy'] },
  { id: 'artistic', label: 'Artistic', color: '#d97706', desc: 'Creative artistic layout with unique visual elements. Perfect for creatives.', tags: ['Art', 'Creative', 'Design'] },
  { id: 'corporate', label: 'Corporate Blue', color: '#1e40af', desc: 'Professional corporate style with blue tones. Ideal for business professionals.', tags: ['Corporate', 'Business', 'Professional'] },
  { id: 'greenergy', label: 'Green Energy', color: '#10b981', desc: 'Eco-friendly theme with green accents. Perfect for sustainability roles.', tags: ['Eco', 'Sustainable', 'Green'] },
  { id: 'purple', label: 'Purple Premium', color: '#a855f7', desc: 'Luxury and premium feel with rich purple accents and sophisticated layout.', tags: ['Premium', 'Luxury', 'Professional'] },
  { id: 'datadriven', label: 'Data-Driven', color: '#3b82f6', desc: 'Analytics and metrics-focused layout. Perfect for data professionals.', tags: ['Analytics', 'Data', 'Tech'] },
  { id: 'wave', label: 'Creative Wave', color: '#06b6d4', desc: 'Dynamic wavy design elements with modern aesthetics and flow.', tags: ['Creative', 'Modern', 'Dynamic'] },
  { id: 'professional', label: 'Professional Pro', color: '#6b7280', desc: 'Advanced professional layout with premium formatting and structure.', tags: ['Professional', 'Advanced', 'Executive'] },
  { id: 'techwave', label: 'Tech Wave', color: '#0891b2', desc: 'Modern tech-forward design with wave patterns and tech aesthetics.', tags: ['Tech', 'Modern', 'Innovation'] },
  { id: 'educational', label: 'Educational', color: '#7c3aed', desc: 'Academic and educational professional layout with emphasis on learning.', tags: ['Education', 'Academic', 'Teaching'] },
  { id: 'consultant', label: 'Consultant', color: '#0d9488', desc: 'Consulting professional layout emphasizing expertise and achievements.', tags: ['Consulting', 'Professional', 'Advisory'] },
  { id: 'creative2', label: 'Creative Plus', color: '#f43f5e', desc: 'Enhanced creative design with modern elements and bold styling.', tags: ['Creative', 'Modern', 'Design'] },
];

export const BUILDER_TEMPLATES = TEMPLATE_CATALOG.filter((template) => template.featured);
